[phases.setup]
aptPkgs = [
  "libsdl2-dev",
  "libsdl2-image-dev",
  "libsdl2-mixer-dev",
  "libsdl2-ttf-dev",
  "xvfb",
  "fontconfig"
]


[start]
cmd = "xvfb-run -a -s '-screen 0 1024x768x24' gunicorn -w 1 -k eventlet -b 0.0.0.0:$PORT app:app"


