[phases.setup]
nixPkgs = [
  "python311",
  "xvfb",
  "SDL2",
  "SDL2_image",
  "SDL2_mixer",
  "SDL2_ttf",
  "fontconfig"
]



[start]
cmd = "xvfb-run -a -s '-screen 0 1024x768x24' gunicorn -w 1 -k eventlet -b 0.0.0.0:$PORT app:app"


