[phases.setup]
nixPkgs = [
  "python311",
  "xorg.xorgserver",      # Provides Xvfb
  "xorg.xf86videodummy",  # Needed for headless rendering
  "SDL2",
  "SDL2_image",
  "SDL2_mixer",
  "SDL2_ttf",
  "fontconfig"
]

[start]
cmd = "Xvfb :99 -screen 0 1024x768x24 & export DISPLAY=:99 && gunicorn -w 1 -k eventlet --timeout 120 -b 0.0.0.0:$PORT app:app"


