[phases.setup]
aptPkgs = [
  "libsdl2-dev",
  "libsdl2-image-dev",
  "libsdl2-mixer-dev",
  "libsdl2-ttf-dev",
  "xvfb"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"
