[phases.setup]
nixPkgs = [
  "python311",
  "xorg.xorgserver",      # Provides Xvfb
  "xorg.xf86videodummy",  # Needed for headless rendering
  "SDL2",
  "SDL2_image",
  "SDL2_mixer",
  "SDL2_ttf",
  "fontconfig"
]

[start]
cmd = 'xvfb-run -s "-screen 0 1024x768x24" python app.py'




