[phases.setup]
nixPkgs = [
  "python311",    # Ensure the correct Python version
  "xvfb",         # Virtual framebuffer for Pygame
  "SDL2",         # Main SDL2 library
  "SDL2_image",   # SDL2 image support
  "SDL2_mixer",   # SDL2 audio mixer
  "SDL2_ttf",     # SDL2 TrueType font support
  "fontconfig"    # Required for font rendering
]


[start]
cmd = "xvfb-run -a -s '-screen 0 1024x768x24' gunicorn -w 1 -k eventlet -b 0.0.0.0:$PORT app:app"


